/* Generated by re2c 0.13.5 */
/**
 * The MIT License
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * @copyright  2009-2011 Roberto Perpuly
 * @license    http://www.opensource.org/licenses/mit-license.php The MIT License
 */
#include <language/LanguageDiscoveryClass.h>
#include <language/Php53LexicalAnalyzerImpl.h>
#include <language/Php53ParserImpl.hpp>

#define DISCOVERY_BUFFER_FILL(n) { Buffer.AppendToLexeme(n); }

#define DISCOVERY_GET_CONDITION() syntax

#define DISCOVERY_SET_CONDITION(c) syntax = c

mvceditor::LanguageDiscoveryClass::LanguageDiscoveryClass()
	: Buffer()
	, Code() {
}

mvceditor::LanguageDiscoveryClass::~LanguageDiscoveryClass() {
	Buffer.Close();
}

bool mvceditor::LanguageDiscoveryClass::Open(const UnicodeString& code) {
	bool ret = Buffer.OpenString(code);
	if (ret) {
		Code = code;
	}
	return ret;
}

mvceditor::LanguageDiscoveryClass::Syntax mvceditor::LanguageDiscoveryClass::at(int pos) {

	// need to reset the buffer back to the beginning of the source code
	Buffer.OpenString(Code);
	int currentPos = 0;
	
	// this variable is used because PHP can be embedded within any part of HTML (tag, attribute or 
	// value) and when we break out of the PHP we need to know what HTML condition we were in
	// for example this line:  < a href="<?php link_to('home'); ?>"
	// in this case when PHP ends we need to go back to the HTML_ATTRIBUTE_VALUE condition 
	mvceditor::LanguageDiscoveryClass::Syntax lastCondition = mvceditor::LanguageDiscoveryClass::SYNTAX_HTML;
	mvceditor::LanguageDiscoveryClass::Syntax syntax = mvceditor::LanguageDiscoveryClass::SYNTAX_HTML;
	
	// Note: the rules below are NOT the full PHP spec; they are only enough rules so that we can
	// properly tell what language we are in.  
	
discovery_start:
	int tokenLength = Buffer.Current - Buffer.TokenStart;
	currentPos += tokenLength;
	if (currentPos >= pos) {
		return syntax;
	}
	
	Buffer.MarkTokenStart();
	
discovery_next_char:

	{
		UChar yych;
		unsigned int yyaccept = 0;
		switch (DISCOVERY_GET_CONDITION()) {
		case SYNTAX_HTML: goto discovery_HTML;
		case SYNTAX_HTML_ATTRIBUTE: goto discovery_HTML_ATTRIBUTE;
		case SYNTAX_HTML_ATTRIBUTE_DOUBLE_QUOTE_VALUE: goto discovery_HTML_ATTRIBUTE_DOUBLE_QUOTE_VALUE;
		case SYNTAX_HTML_ATTRIBUTE_SINGLE_QUOTE_VALUE: goto discovery_HTML_ATTRIBUTE_SINGLE_QUOTE_VALUE;
		case SYNTAX_HTML_ENTITY: goto discovery_HTML_ENTITY;
		case SYNTAX_HTML_TAG: goto discovery_HTML_TAG;
		case SYNTAX_PHP_BACKTICK: goto discovery_PHP_BACKTICK;
		case SYNTAX_PHP_DOUBLE_QUOTE_STRING: goto discovery_PHP_DOUBLE_QUOTE_STRING;
		case SYNTAX_PHP_HEREDOC: goto discovery_PHP_HEREDOC;
		case SYNTAX_PHP_LINE_COMMENT: goto discovery_PHP_LINE_COMMENT;
		case SYNTAX_PHP_MULTI_LINE_COMMENT: goto discovery_PHP_MULTI_LINE_COMMENT;
		case SYNTAX_PHP_NOWDOC: goto discovery_PHP_NOWDOC;
		case SYNTAX_PHP_SCRIPT: goto discovery_PHP_SCRIPT;
		case SYNTAX_PHP_SINGLE_QUOTE_STRING: goto discovery_PHP_SINGLE_QUOTE_STRING;
		}
/* *********************************** */
discovery_HTML:

		if ((Buffer.Limit - Buffer.Current) < 7) DISCOVERY_BUFFER_FILL(7);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_2;
		case '\n':	goto discovery_6;
		case '\r':	goto discovery_8;
		case '&':	goto discovery_9;
		case '<':	goto discovery_4;
		default:	goto discovery_11;
		}
discovery_2:
		++Buffer.Current;
		{ return syntax; }
discovery_4:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '?':	goto discovery_14;
		default:	goto discovery_5;
		}
discovery_5:
		{ syntax = SYNTAX_HTML_TAG; goto discovery_start; }
discovery_6:
		++Buffer.Current;
discovery_7:
		{ Buffer.IncrementLine(); goto discovery_start; }
discovery_8:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_13;
		default:	goto discovery_7;
		}
discovery_9:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML_ENTITY; goto discovery_start; }
discovery_11:
		++Buffer.Current;
		{ goto discovery_start; }
discovery_13:
		yych = *++Buffer.Current;
		goto discovery_7;
discovery_14:
		yyaccept = 0;
		yych = *(Buffer.Marker = ++Buffer.Current);
		switch (yych) {
		case '=':	goto discovery_18;
		case 'P':
		case 'p':	goto discovery_16;
		default:	goto discovery_15;
		}
discovery_15:
		{ lastCondition = SYNTAX_HTML; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_16:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'H':
		case 'h':	goto discovery_20;
		default:	goto discovery_17;
		}
discovery_17:
		Buffer.Current = Buffer.Marker;
		goto discovery_15;
discovery_18:
		++Buffer.Current;
		{ lastCondition = SYNTAX_HTML; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_20:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'P':
		case 'p':	goto discovery_21;
		default:	goto discovery_17;
		}
discovery_21:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ':	goto discovery_22;
		case '\r':	goto discovery_24;
		default:	goto discovery_17;
		}
discovery_22:
		++Buffer.Current;
discovery_23:
		{ lastCondition = SYNTAX_HTML; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_24:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '\n':	goto discovery_22;
		default:	goto discovery_23;
		}
/* *********************************** */
discovery_HTML_ATTRIBUTE:
		if ((Buffer.Limit - Buffer.Current) < 7) DISCOVERY_BUFFER_FILL(7);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_27;
		case '/':	goto discovery_32;
		case '<':	goto discovery_29;
		case '=':	goto discovery_31;
		case '>':	goto discovery_33;
		default:	goto discovery_35;
		}
discovery_27:
		++Buffer.Current;
		{ return syntax; }
discovery_29:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '?':	goto discovery_47;
		default:	goto discovery_30;
		}
discovery_30:
		{ goto discovery_start; }
discovery_31:
		yyaccept = 0;
		yych = *(Buffer.Marker = ++Buffer.Current);
		switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ':
		case '"':
		case '\'':	goto discovery_39;
		default:	goto discovery_30;
		}
discovery_32:
		yych = *++Buffer.Current;
		switch (yych) {
		case '>':	goto discovery_36;
		default:	goto discovery_30;
		}
discovery_33:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML; goto discovery_start; }
discovery_35:
		yych = *++Buffer.Current;
		goto discovery_30;
discovery_36:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML; goto discovery_start; }
discovery_38:
		++Buffer.Current;
		if (Buffer.Limit <= Buffer.Current) DISCOVERY_BUFFER_FILL(1);
		yych = *Buffer.Current;
discovery_39:
		switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ':	goto discovery_38;
		case '\r':	goto discovery_41;
		case '"':	goto discovery_45;
		case '\'':	goto discovery_43;
		default:	goto discovery_40;
		}
discovery_40:
		Buffer.Current = Buffer.Marker;
		switch (yyaccept) {
		case 0: 	goto discovery_30;
		case 1: 	goto discovery_48;
		}
discovery_41:
		++Buffer.Current;
		if (Buffer.Limit <= Buffer.Current) DISCOVERY_BUFFER_FILL(1);
		yych = *Buffer.Current;
		switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ':	goto discovery_38;
		case '\r':	goto discovery_41;
		case '"':	goto discovery_45;
		case '\'':	goto discovery_43;
		default:	goto discovery_40;
		}
discovery_43:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML_ATTRIBUTE_SINGLE_QUOTE_VALUE; goto discovery_start; }
discovery_45:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML_ATTRIBUTE_DOUBLE_QUOTE_VALUE; goto discovery_start; }
discovery_47:
		yyaccept = 1;
		yych = *(Buffer.Marker = ++Buffer.Current);
		switch (yych) {
		case '=':	goto discovery_50;
		case 'P':
		case 'p':	goto discovery_49;
		default:	goto discovery_48;
		}
discovery_48:
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_49:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'H':
		case 'h':	goto discovery_52;
		default:	goto discovery_40;
		}
discovery_50:
		++Buffer.Current;
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_52:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'P':
		case 'p':	goto discovery_53;
		default:	goto discovery_40;
		}
discovery_53:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ':	goto discovery_54;
		case '\r':	goto discovery_56;
		default:	goto discovery_40;
		}
discovery_54:
		++Buffer.Current;
discovery_55:
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_56:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '\n':	goto discovery_54;
		default:	goto discovery_55;
		}
/* *********************************** */
discovery_HTML_ATTRIBUTE_DOUBLE_QUOTE_VALUE:
		if ((Buffer.Limit - Buffer.Current) < 7) DISCOVERY_BUFFER_FILL(7);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_59;
		case '"':	goto discovery_64;
		case '<':	goto discovery_61;
		case '\\':	goto discovery_63;
		default:	goto discovery_66;
		}
discovery_59:
		++Buffer.Current;
		{ return syntax; }
discovery_61:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '?':	goto discovery_69;
		default:	goto discovery_62;
		}
discovery_62:
		{ goto discovery_start; }
discovery_63:
		yych = *++Buffer.Current;
		switch (yych) {
		case '"':	goto discovery_67;
		default:	goto discovery_62;
		}
discovery_64:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML_ATTRIBUTE; goto discovery_start; }
discovery_66:
		yych = *++Buffer.Current;
		goto discovery_62;
discovery_67:
		++Buffer.Current;
		{ goto discovery_start; }
discovery_69:
		yyaccept = 0;
		yych = *(Buffer.Marker = ++Buffer.Current);
		switch (yych) {
		case '=':	goto discovery_73;
		case 'P':
		case 'p':	goto discovery_71;
		default:	goto discovery_70;
		}
discovery_70:
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE_DOUBLE_QUOTE_VALUE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_71:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'H':
		case 'h':	goto discovery_75;
		default:	goto discovery_72;
		}
discovery_72:
		Buffer.Current = Buffer.Marker;
		goto discovery_70;
discovery_73:
		++Buffer.Current;
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE_DOUBLE_QUOTE_VALUE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_75:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'P':
		case 'p':	goto discovery_76;
		default:	goto discovery_72;
		}
discovery_76:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ':	goto discovery_77;
		case '\r':	goto discovery_79;
		default:	goto discovery_72;
		}
discovery_77:
		++Buffer.Current;
discovery_78:
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE_DOUBLE_QUOTE_VALUE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_79:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '\n':	goto discovery_77;
		default:	goto discovery_78;
		}
/* *********************************** */
discovery_HTML_ATTRIBUTE_SINGLE_QUOTE_VALUE:
		if ((Buffer.Limit - Buffer.Current) < 7) DISCOVERY_BUFFER_FILL(7);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_82;
		case '\'':	goto discovery_87;
		case '<':	goto discovery_84;
		case '\\':	goto discovery_86;
		default:	goto discovery_89;
		}
discovery_82:
		++Buffer.Current;
		{ return syntax; }
discovery_84:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '?':	goto discovery_92;
		default:	goto discovery_85;
		}
discovery_85:
		{ goto discovery_start; }
discovery_86:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\'':	goto discovery_90;
		default:	goto discovery_85;
		}
discovery_87:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML_ATTRIBUTE; goto discovery_start; }
discovery_89:
		yych = *++Buffer.Current;
		goto discovery_85;
discovery_90:
		++Buffer.Current;
		{ goto discovery_start; }
discovery_92:
		yyaccept = 0;
		yych = *(Buffer.Marker = ++Buffer.Current);
		switch (yych) {
		case '=':	goto discovery_96;
		case 'P':
		case 'p':	goto discovery_94;
		default:	goto discovery_93;
		}
discovery_93:
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE_SINGLE_QUOTE_VALUE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_94:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'H':
		case 'h':	goto discovery_98;
		default:	goto discovery_95;
		}
discovery_95:
		Buffer.Current = Buffer.Marker;
		goto discovery_93;
discovery_96:
		++Buffer.Current;
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE_SINGLE_QUOTE_VALUE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_98:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'P':
		case 'p':	goto discovery_99;
		default:	goto discovery_95;
		}
discovery_99:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ':	goto discovery_100;
		case '\r':	goto discovery_102;
		default:	goto discovery_95;
		}
discovery_100:
		++Buffer.Current;
discovery_101:
		{ lastCondition = SYNTAX_HTML_ATTRIBUTE_SINGLE_QUOTE_VALUE; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_102:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '\n':	goto discovery_100;
		default:	goto discovery_101;
		}
/* *********************************** */
discovery_HTML_ENTITY:
		if ((Buffer.Limit - Buffer.Current) < 2) DISCOVERY_BUFFER_FILL(2);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_105;
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ':	goto discovery_107;
		case '\r':	goto discovery_109;
		default:	goto discovery_110;
		}
discovery_105:
		++Buffer.Current;
		{ return syntax; }
discovery_107:
		++Buffer.Current;
discovery_108:
		{ syntax = SYNTAX_HTML; goto discovery_start; }
discovery_109:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_112;
		default:	goto discovery_108;
		}
discovery_110:
		++Buffer.Current;
		{ goto discovery_start; }
discovery_112:
		++Buffer.Current;
		yych = *Buffer.Current;
		goto discovery_108;
/* *********************************** */
discovery_HTML_TAG:
		if ((Buffer.Limit - Buffer.Current) < 7) DISCOVERY_BUFFER_FILL(7);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_115;
		case '\t':
		case '\v':
		case '\f':
		case ' ':	goto discovery_119;
		case '\n':	goto discovery_121;
		case '\r':	goto discovery_123;
		case '/':	goto discovery_124;
		case '<':	goto discovery_117;
		case '>':	goto discovery_125;
		default:	goto discovery_127;
		}
discovery_115:
		++Buffer.Current;
		{ return syntax; }
discovery_117:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '?':	goto discovery_131;
		default:	goto discovery_118;
		}
discovery_118:
		{ goto discovery_start; }
discovery_119:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML_ATTRIBUTE; goto discovery_start; }
discovery_121:
		++Buffer.Current;
discovery_122:
		{ Buffer.IncrementLine(); syntax = SYNTAX_HTML_ATTRIBUTE; goto discovery_start; }
discovery_123:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_130;
		default:	goto discovery_122;
		}
discovery_124:
		yych = *++Buffer.Current;
		switch (yych) {
		case '>':	goto discovery_128;
		default:	goto discovery_118;
		}
discovery_125:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML; goto discovery_start; }
discovery_127:
		yych = *++Buffer.Current;
		goto discovery_118;
discovery_128:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML; goto discovery_start; }
discovery_130:
		yych = *++Buffer.Current;
		goto discovery_122;
discovery_131:
		yyaccept = 0;
		yych = *(Buffer.Marker = ++Buffer.Current);
		switch (yych) {
		case '=':	goto discovery_135;
		case 'P':
		case 'p':	goto discovery_133;
		default:	goto discovery_132;
		}
discovery_132:
		{ lastCondition = SYNTAX_HTML_TAG; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_133:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'H':
		case 'h':	goto discovery_137;
		default:	goto discovery_134;
		}
discovery_134:
		Buffer.Current = Buffer.Marker;
		goto discovery_132;
discovery_135:
		++Buffer.Current;
		{ lastCondition = SYNTAX_HTML_TAG; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_137:
		yych = *++Buffer.Current;
		switch (yych) {
		case 'P':
		case 'p':	goto discovery_138;
		default:	goto discovery_134;
		}
discovery_138:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ':	goto discovery_139;
		case '\r':	goto discovery_141;
		default:	goto discovery_134;
		}
discovery_139:
		++Buffer.Current;
discovery_140:
		{ lastCondition = SYNTAX_HTML_TAG; syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_141:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '\n':	goto discovery_139;
		default:	goto discovery_140;
		}
/* *********************************** */
discovery_PHP_BACKTICK:
		if ((Buffer.Limit - Buffer.Current) < 2) DISCOVERY_BUFFER_FILL(2);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_144;
		case '\n':	goto discovery_148;
		case '\r':	goto discovery_150;
		case '`':	goto discovery_146;
		default:	goto discovery_151;
		}
discovery_144:
		++Buffer.Current;
		{ return syntax; }
discovery_146:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_148:
		++Buffer.Current;
discovery_149:
		{ Buffer.IncrementLine(); goto discovery_start; }
discovery_150:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_153;
		default:	goto discovery_149;
		}
discovery_151:
		++Buffer.Current;
		{ goto discovery_start; }
discovery_153:
		++Buffer.Current;
		yych = *Buffer.Current;
		goto discovery_149;
/* *********************************** */
discovery_PHP_DOUBLE_QUOTE_STRING:
		if ((Buffer.Limit - Buffer.Current) < 2) DISCOVERY_BUFFER_FILL(2);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_156;
		case '\n':	goto discovery_162;
		case '\r':	goto discovery_164;
		case '"':	goto discovery_160;
		case '\\':	goto discovery_158;
		default:	goto discovery_165;
		}
discovery_156:
		++Buffer.Current;
		{ return syntax; }
discovery_158:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '"':	goto discovery_169;
		case '\\':	goto discovery_167;
		default:	goto discovery_159;
		}
discovery_159:
		{ goto discovery_start; }
discovery_160:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_SCRIPT; }
discovery_162:
		++Buffer.Current;
discovery_163:
		{ Buffer.IncrementLine(); goto discovery_start; }
discovery_164:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_166;
		default:	goto discovery_163;
		}
discovery_165:
		yych = *++Buffer.Current;
		goto discovery_159;
discovery_166:
		yych = *++Buffer.Current;
		goto discovery_163;
discovery_167:
		++Buffer.Current;
		{ goto discovery_start; }
discovery_169:
		++Buffer.Current;
		{ goto discovery_start; }
/* *********************************** */
discovery_PHP_HEREDOC:
		if (Buffer.Limit <= Buffer.Current) DISCOVERY_BUFFER_FILL(1);
		yych = *Buffer.Current;
		if (yych >= 0x01) goto discovery_175;
		++Buffer.Current;
		{ return syntax; }
discovery_175:
		++Buffer.Current;
		{ if (mvceditor::HandleHeredoc(&Buffer) == T_ERROR_UNTERMINATED_STRING || (currentPos + (Buffer.Current - Buffer.TokenStart)) >= pos)  { return syntax ; } syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
/* *********************************** */
discovery_PHP_LINE_COMMENT:
		if ((Buffer.Limit - Buffer.Current) < 2) DISCOVERY_BUFFER_FILL(2);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_179;
		case '\n':	goto discovery_181;
		case '\r':	goto discovery_183;
		case '?':	goto discovery_184;
		default:	goto discovery_186;
		}
discovery_179:
		++Buffer.Current;
		{ return syntax; }
discovery_181:
		++Buffer.Current;
discovery_182:
		{ Buffer.IncrementLine(); syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_183:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_189;
		default:	goto discovery_182;
		}
discovery_184:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '>':	goto discovery_187;
		default:	goto discovery_185;
		}
discovery_185:
		{ goto discovery_start; }
discovery_186:
		yych = *++Buffer.Current;
		goto discovery_185;
discovery_187:
		++Buffer.Current;
		{ syntax = SYNTAX_HTML; goto discovery_start; }
discovery_189:
		++Buffer.Current;
		yych = *Buffer.Current;
		goto discovery_182;
/* *********************************** */
discovery_PHP_MULTI_LINE_COMMENT:
		if ((Buffer.Limit - Buffer.Current) < 2) DISCOVERY_BUFFER_FILL(2);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_192;
		case '\n':	goto discovery_194;
		case '\r':	goto discovery_196;
		case '*':	goto discovery_197;
		default:	goto discovery_199;
		}
discovery_192:
		++Buffer.Current;
		{ return syntax; }
discovery_194:
		++Buffer.Current;
discovery_195:
		{ Buffer.IncrementLine(); goto discovery_start; }
discovery_196:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_202;
		default:	goto discovery_195;
		}
discovery_197:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '/':	goto discovery_200;
		default:	goto discovery_198;
		}
discovery_198:
		{ goto discovery_start; }
discovery_199:
		yych = *++Buffer.Current;
		goto discovery_198;
discovery_200:
		++Buffer.Current;
		{  syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_202:
		++Buffer.Current;
		yych = *Buffer.Current;
		goto discovery_195;
/* *********************************** */
discovery_PHP_NOWDOC:
		if (Buffer.Limit <= Buffer.Current) DISCOVERY_BUFFER_FILL(1);
		yych = *Buffer.Current;
		if (yych >= 0x01) goto discovery_207;
		++Buffer.Current;
		{ return syntax; }
discovery_207:
		++Buffer.Current;
		{ if (mvceditor::HandleNowdoc(&Buffer) == T_ERROR_UNTERMINATED_STRING || (currentPos + (Buffer.Current - Buffer.TokenStart)) >= pos) { return syntax; } syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
/* *********************************** */
discovery_PHP_SCRIPT:
		if ((Buffer.Limit - Buffer.Current) < 3) DISCOVERY_BUFFER_FILL(3);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_211;
		case '"':	goto discovery_220;
		case '#':	goto discovery_216;
		case '\'':	goto discovery_218;
		case '/':	goto discovery_215;
		case '<':	goto discovery_224;
		case '?':	goto discovery_213;
		case '`':	goto discovery_222;
		default:	goto discovery_225;
		}
discovery_211:
		++Buffer.Current;
		{ return syntax; }
discovery_213:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '>':	goto discovery_250;
		default:	goto discovery_214;
		}
discovery_214:
		{ goto discovery_start; }
discovery_215:
		yych = *++Buffer.Current;
		switch (yych) {
		case '*':	goto discovery_246;
		case '/':	goto discovery_248;
		default:	goto discovery_214;
		}
discovery_216:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_LINE_COMMENT; goto discovery_start;}
discovery_218:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_SINGLE_QUOTE_STRING; goto discovery_start;}
discovery_220:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_DOUBLE_QUOTE_STRING; goto discovery_start;}
discovery_222:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_BACKTICK; goto discovery_start;}
discovery_224:
		yyaccept = 0;
		yych = *(Buffer.Marker = ++Buffer.Current);
		switch (yych) {
		case '<':	goto discovery_226;
		default:	goto discovery_214;
		}
discovery_225:
		yych = *++Buffer.Current;
		goto discovery_214;
discovery_226:
		yych = *++Buffer.Current;
		switch (yych) {
		case '<':	goto discovery_228;
		default:	goto discovery_227;
		}
discovery_227:
		Buffer.Current = Buffer.Marker;
		goto discovery_214;
discovery_228:
		++Buffer.Current;
		if ((Buffer.Limit - Buffer.Current) < 2) DISCOVERY_BUFFER_FILL(2);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\n':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '!':
		case '#':
		case '$':
		case '%':
		case '&':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto discovery_227;
		case '\t':
		case '\v':
		case '\f':
		case ' ':	goto discovery_228;
		case '"':	goto discovery_231;
		case '\'':	goto discovery_230;
		default:	goto discovery_232;
		}
discovery_230:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\'':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto discovery_227;
		default:	goto discovery_241;
		}
discovery_231:
		yych = *++Buffer.Current;
		switch (yych) {
		case '"':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto discovery_227;
		default:	goto discovery_238;
		}
discovery_232:
		++Buffer.Current;
		if ((Buffer.Limit - Buffer.Current) < 2) DISCOVERY_BUFFER_FILL(2);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto discovery_227;
		case '\n':	goto discovery_234;
		case '\r':	goto discovery_236;
		default:	goto discovery_232;
		}
discovery_234:
		++Buffer.Current;
discovery_235:
		{ Buffer.IncrementLine(); syntax = SYNTAX_PHP_HEREDOC; goto discovery_next_char; }
discovery_236:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_234;
		default:	goto discovery_235;
		}
discovery_237:
		++Buffer.Current;
		if ((Buffer.Limit - Buffer.Current) < 3) DISCOVERY_BUFFER_FILL(3);
		yych = *Buffer.Current;
discovery_238:
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto discovery_227;
		case '"':	goto discovery_239;
		default:	goto discovery_237;
		}
discovery_239:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_234;
		case '\r':	goto discovery_236;
		default:	goto discovery_227;
		}
discovery_240:
		++Buffer.Current;
		if ((Buffer.Limit - Buffer.Current) < 3) DISCOVERY_BUFFER_FILL(3);
		yych = *Buffer.Current;
discovery_241:
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '|':
		case '}':
		case '~':	goto discovery_227;
		case '\'':	goto discovery_242;
		default:	goto discovery_240;
		}
discovery_242:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_243;
		case '\r':	goto discovery_245;
		default:	goto discovery_227;
		}
discovery_243:
		++Buffer.Current;
discovery_244:
		{ Buffer.IncrementLine(); syntax = SYNTAX_PHP_NOWDOC; goto discovery_next_char; }
discovery_245:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_243;
		default:	goto discovery_244;
		}
discovery_246:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_MULTI_LINE_COMMENT; goto discovery_start;}
discovery_248:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_LINE_COMMENT; goto discovery_start;}
discovery_250:
		++Buffer.Current;
		{ syntax = lastCondition; goto discovery_start; }
/* *********************************** */
discovery_PHP_SINGLE_QUOTE_STRING:
		if ((Buffer.Limit - Buffer.Current) < 2) DISCOVERY_BUFFER_FILL(2);
		yych = *Buffer.Current;
		switch (yych) {
		case 0x00:	goto discovery_254;
		case '\n':	goto discovery_260;
		case '\r':	goto discovery_262;
		case '\'':	goto discovery_258;
		case '\\':	goto discovery_256;
		default:	goto discovery_263;
		}
discovery_254:
		++Buffer.Current;
		{ return syntax; }
discovery_256:
		++Buffer.Current;
		switch ((yych = *Buffer.Current)) {
		case '\'':	goto discovery_267;
		case '\\':	goto discovery_265;
		default:	goto discovery_257;
		}
discovery_257:
		{ goto discovery_start; }
discovery_258:
		++Buffer.Current;
		{ syntax = SYNTAX_PHP_SCRIPT; goto discovery_start; }
discovery_260:
		++Buffer.Current;
discovery_261:
		{ Buffer.IncrementLine(); goto discovery_start; }
discovery_262:
		yych = *++Buffer.Current;
		switch (yych) {
		case '\n':	goto discovery_264;
		default:	goto discovery_261;
		}
discovery_263:
		yych = *++Buffer.Current;
		goto discovery_257;
discovery_264:
		yych = *++Buffer.Current;
		goto discovery_261;
discovery_265:
		++Buffer.Current;
		{ goto discovery_start; }
discovery_267:
		++Buffer.Current;
		{ goto discovery_start; }
	}


}